version: '3'

services:
  db:
    image: mysql:latest
    ports:
      - "3305:3305"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'DB1'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:9000
    ports:
      - 9000:9000
    depends_on:
      - db