# Generated by Django 3.0.6 on 2020-06-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SALES_DATA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Description', models.CharField(max_length=50)),
                ('Item_Type', models.CharField(max_length=30)),
                ('Customer_Name', models.IntegerField()),
                ('Company_Name', models.CharField(max_length=100)),
                ('Amount', models.IntegerField()),
                ('Rate', models.FloatField()),
                ('Status', models.BooleanField()),
                ('Sale_Date', models.DateField()),
                ('User', models.CharField(max_length=50)),
            ],
        ),
    ]
