# Generated by Django 3.0.6 on 2020-06-05 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_data',
            old_name='User',
            new_name='Username',
        ),
    ]
