# Generated by Django 3.0.6 on 2020-06-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Customer_ID',
            field=models.IntegerField(),
        ),
    ]
