# Generated by Django 3.0.6 on 2020-06-11 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200608_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Customer_Type_ID',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Customer_ID',
            field=models.IntegerField(),
        ),
    ]
