# Generated by Django 3.0.6 on 2020-06-11 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200611_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_Type_ID',
            new_name='Customer_Type',
        ),
    ]
