# Generated by Django 3.0.6 on 2020-06-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='purchase',
        ),
    ]
