# Generated by Django 3.0.6 on 2020-06-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Description', models.CharField(max_length=50)),
                ('Item_Type', models.CharField(max_length=30)),
                ('Vendor_Name', models.IntegerField()),
                ('Company_Name', models.CharField(max_length=100)),
                ('Amount', models.IntegerField()),
                ('Rate', models.FloatField()),
                ('Status', models.BooleanField()),
                ('Purchase_Date', models.DateField()),
                ('Username', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=150)),
            ],
        ),
    ]
